### PR TITLE
test features in ci

### PR DESCRIPTION
**Pull request by Erik1000**

### CODE REVIEW

**Comment by Erik1000** [comment]
bors try

**Comment by Erik1000** [comment]
bors try

**Comment by Erik1000** [comment]
bors cancel

**Comment by Erik1000** [comment]
bors try

**Comment by Erik1000** [comment]
bors retry

**Comment by Erik1000** [comment]
bors try-

**Comment by Erik1000** [comment]
bors try

**Comment by Erik1000** [comment]
bors try-

**Comment by Erik1000** [comment]
bors try

**Comment by Erik1000** [comment]
bors try-

**Comment by Erik1000** [comment]
bors try

**Comment by Erik1000** [comment]
bors try

**Comment by Erik1000** [comment]
bors try

**Comment by Erik1000** [comment]
bors try

**Comment by Erik1000** [comment]
bors try

**Review by Stupremee — APPROVED** [review]

**Pull request merged**
